# Generated by Django 5.1.6 on 2025-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevant_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relevant Text'),
        ),
    ]
