# Generated by Django 5.1.6 on 2026-02-05 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='relevant_text',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Relevant Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Title'),
        ),
    ]
